DROP TABLE PUBLIC.EMPLOYEE IF EXISTS;
CREATE TABLE PUBLIC.EMPLOYEE (
  
   first_name VARCHAR(20) default NULL,
   last_name  VARCHAR(20) default NULL,
   salary     INT  default NULL,
  -- PRIMARY KEY (id)
 	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);


INSERT INTO EMPLOYEE(ID,first_name,last_name,salary) VALUES (0,'Paco','Vera',301.00);
INSERT INTO EMPLOYEE(ID,first_name,last_name,salary) VALUES (1,'Susana','Sigler',256.00);
INSERT INTO EMPLOYEE(ID,first_name,last_name,salary) VALUES (2,'Ana','del carpio',456.00);
INSERT INTO EMPLOYEE(ID,first_name,last_name,salary) VALUES (3,'Michael','Foucut',345.89);
INSERT INTO EMPLOYEE(ID,first_name,last_name,salary) VALUES (4,'Silvia','Saint',456.98);
